name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: 
          echo "Hello World!"
          echo " Git ref = ${{ github.ref }}"
          echo "ssh url = ${{ github.ssh_url }}"
          echo "ssh repository url = ${{ github.repository.ssh_url }}"